from welcome_page import handle_request as welcome_page_handle_request
from file_upload import handle_request as file_upload_handle_request
from magic8ball import handle_request as magic8ball_handle_request
from chatroom import handle_request as chat_room_handle_request
